// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb/echo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	UnarySay(ctx context.Context, in *UnarySayRequest, opts ...grpc.CallOption) (*UnarySayResponse, error)
	StreamSay(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamSayClient, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) UnarySay(ctx context.Context, in *UnarySayRequest, opts ...grpc.CallOption) (*UnarySayResponse, error) {
	out := new(UnarySayResponse)
	err := c.cc.Invoke(ctx, "/pb.Echo/UnarySay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) StreamSay(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamSayClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], "/pb.Echo/StreamSay", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoStreamSayClient{stream}
	return x, nil
}

type Echo_StreamSayClient interface {
	Send(*StreamSayRequest) error
	Recv() (*StreamSayResponse, error)
	grpc.ClientStream
}

type echoStreamSayClient struct {
	grpc.ClientStream
}

func (x *echoStreamSayClient) Send(m *StreamSayRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoStreamSayClient) Recv() (*StreamSayResponse, error) {
	m := new(StreamSayResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	UnarySay(context.Context, *UnarySayRequest) (*UnarySayResponse, error)
	StreamSay(Echo_StreamSayServer) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) UnarySay(context.Context, *UnarySayRequest) (*UnarySayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnarySay not implemented")
}
func (UnimplementedEchoServer) StreamSay(Echo_StreamSayServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSay not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_UnarySay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarySayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).UnarySay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Echo/UnarySay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).UnarySay(ctx, req.(*UnarySayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_StreamSay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).StreamSay(&echoStreamSayServer{stream})
}

type Echo_StreamSayServer interface {
	Send(*StreamSayResponse) error
	Recv() (*StreamSayRequest, error)
	grpc.ServerStream
}

type echoStreamSayServer struct {
	grpc.ServerStream
}

func (x *echoStreamSayServer) Send(m *StreamSayResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoStreamSayServer) Recv() (*StreamSayRequest, error) {
	m := new(StreamSayRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnarySay",
			Handler:    _Echo_UnarySay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSay",
			Handler:       _Echo_StreamSay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/echo.proto",
}
