// protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./pb/echo.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pb/echo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnarySayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req string `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *UnarySayRequest) Reset() {
	*x = UnarySayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnarySayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarySayRequest) ProtoMessage() {}

func (x *UnarySayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarySayRequest.ProtoReflect.Descriptor instead.
func (*UnarySayRequest) Descriptor() ([]byte, []int) {
	return file_pb_echo_proto_rawDescGZIP(), []int{0}
}

func (x *UnarySayRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type UnarySayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *UnarySayResponse) Reset() {
	*x = UnarySayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_echo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnarySayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarySayResponse) ProtoMessage() {}

func (x *UnarySayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_echo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarySayResponse.ProtoReflect.Descriptor instead.
func (*UnarySayResponse) Descriptor() ([]byte, []int) {
	return file_pb_echo_proto_rawDescGZIP(), []int{1}
}

func (x *UnarySayResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type StreamSayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req string `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *StreamSayRequest) Reset() {
	*x = StreamSayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_echo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamSayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSayRequest) ProtoMessage() {}

func (x *StreamSayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_echo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSayRequest.ProtoReflect.Descriptor instead.
func (*StreamSayRequest) Descriptor() ([]byte, []int) {
	return file_pb_echo_proto_rawDescGZIP(), []int{2}
}

func (x *StreamSayRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type StreamSayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *StreamSayResponse) Reset() {
	*x = StreamSayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_echo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamSayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSayResponse) ProtoMessage() {}

func (x *StreamSayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_echo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSayResponse.ProtoReflect.Descriptor instead.
func (*StreamSayResponse) Descriptor() ([]byte, []int) {
	return file_pb_echo_proto_rawDescGZIP(), []int{3}
}

func (x *StreamSayResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_pb_echo_proto protoreflect.FileDescriptor

var file_pb_echo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x23, 0x0a, 0x0f, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x10, 0x55, 0x6e, 0x61, 0x72,
	0x79, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x24, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32,
	0x7b, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x35, 0x0a, 0x08, 0x55, 0x6e, 0x61, 0x72, 0x79,
	0x53, 0x61, 0x79, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x61,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x61, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_echo_proto_rawDescOnce sync.Once
	file_pb_echo_proto_rawDescData = file_pb_echo_proto_rawDesc
)

func file_pb_echo_proto_rawDescGZIP() []byte {
	file_pb_echo_proto_rawDescOnce.Do(func() {
		file_pb_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_echo_proto_rawDescData)
	})
	return file_pb_echo_proto_rawDescData
}

var file_pb_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_echo_proto_goTypes = []interface{}{
	(*UnarySayRequest)(nil),   // 0: pb.UnarySayRequest
	(*UnarySayResponse)(nil),  // 1: pb.UnarySayResponse
	(*StreamSayRequest)(nil),  // 2: pb.StreamSayRequest
	(*StreamSayResponse)(nil), // 3: pb.StreamSayResponse
}
var file_pb_echo_proto_depIdxs = []int32{
	0, // 0: pb.Echo.UnarySay:input_type -> pb.UnarySayRequest
	2, // 1: pb.Echo.StreamSay:input_type -> pb.StreamSayRequest
	1, // 2: pb.Echo.UnarySay:output_type -> pb.UnarySayResponse
	3, // 3: pb.Echo.StreamSay:output_type -> pb.StreamSayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_echo_proto_init() }
func file_pb_echo_proto_init() {
	if File_pb_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnarySayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_echo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnarySayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_echo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamSayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_echo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamSayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_echo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_echo_proto_goTypes,
		DependencyIndexes: file_pb_echo_proto_depIdxs,
		MessageInfos:      file_pb_echo_proto_msgTypes,
	}.Build()
	File_pb_echo_proto = out.File
	file_pb_echo_proto_rawDesc = nil
	file_pb_echo_proto_goTypes = nil
	file_pb_echo_proto_depIdxs = nil
}
