version: "3.0"

# 网络
networks:
  jaeger-net: 
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    restart: always
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      TZ: Asia/Shanghai
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - jaeger-net