version: '3.7'

services:

  redis:
    image: redis:5.0.14-alpine
    container_name: redis
    restart: unless-stopped
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis:/etc/redis:rw
      - ./redis/sysctl.conf:/etc/sysctl.conf:rw
    networks:
      redisnet:
    command: redis-server /etc/redis/redis.conf --save 60 1 --loglevel warning

networks:
  redisnet: