version: "3.2"

services:
    zookeeper:
        image: zookeeper:latest
        restart: always
        container_name: zookeeper
        ports:
            - "2181:2181"
        expose:
            - "2181"
        environment:
            - ZOO_MY_ID=1
        volumes:
            - "./data/zookeeper/data:/data:rw"
            - "./data/zookeeper/datalog:/datalog:rw"
        networks:
            kafkanet:

    kafka:
        image: wurstmeister/kafka:latest
        restart: always
        container_name: kafka
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_MESSAGE_MAX_BYTES=2000000
            - KAFKA_ADVERTISED_HOST_NAME=172.25.143.184
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_DELETE_TOPIC_ENABLE=true
        volumes:
            - "./data/kafka:/kafka:rw"
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        networks:
            kafkanet:

networks:
    kafkanet:
